name: Build and deploy to Azure Spring Apps

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
        check-latest: false
        cache: 'maven'
    - name: Build with Maven
      run: mvn package -DskipTests
    - name: Login to Azure Spring Apps
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Get Subscription ID
      run: |
        echo "SUBSCRIPTION_ID=$(az account show --query id --output tsv --only-show-errors)" >> $GITHUB_ENV
      shell: bash
    - name: Deploy to Azure Spring Apps
      uses: azure/spring-cloud-deploy@v1
      with:
        action: deploy
        azure-subscription: ${{ env.SUBSCRIPTION_ID }}
        service-name: mkheck-a-s-a-labs
        app-name: weather-service
        use-staging-deployment: false
        package: target/demo-0.0.1-SNAPSHOT.jar
